language: node_js
node_js:
  - "10"
  - "11"
  - "12"
install:
  - npm install
script:
  - npm run check
  - npm run build
  - npm run validate
after_success:
  - npm run coveralls
  - npm run github-release
