language: node_js
node_js:
  - "10"
  - "11"
  - "12"
install:
  - npm install
script:
  - npm run audit
  - npm run outdated
  - npm run build
  - npm run lint
  - npm run test
after_success:
  - npm run coveralls
  - npm run github-release
